### ISSUE TITLE
ModuleNotFoundError for PyPi puft installation for absolute imports at the build.py

### ISSUE THREAD

**Issue by ryzhovalex** [ryzhovalex/omen#3]
Reproduce:
Install puft from PyPi and try to call `puft dev` on any custom app's build.py with relative import.

Temporary fix:
```shell
export PYTHONPATH=/path/to/your/app
```

**Comment by ryzhovalex** [comment]
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/puft-test/bin/puft", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.virtualenvs/puft-test/lib/python3.10/site-packages/puft/helpers/cli.py", line 34, in main
    assembler = spawn_assembler(
  File "/home/alex/.virtualenvs/puft-test/lib/python3.10/site-packages/puft/helpers/cli.py", line 73, in spawn_assembler
    module_spec.loader.exec_module(main_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/testapp/build.py", line 4, in <module>
    from src.models.domains.orm import SomeObj as SomeObjORM
ModuleNotFoundError: No module named 'src'

**Comment by ryzhovalex** [comment]
Possible but not clean solution: append module path to sys.path of puft.cli.py

**Comment by ryzhovalex** [comment]
Fixed by https://github.com/ryzhovalex/puft/commit/cdef06efe340c26630f66d42f344755172d8d62f
