### ISSUE TITLE
ModuleNotFoundError: No module named 'puft.errors'

### ISSUE THREAD

**Issue by ryzhovalex** [ryzhovalex/omen#5]
#### Reproduce
1. Make manual installation:
```shell
pip install -r requirements.txt
python3.10 setup.py install
```
2. Call puft:
```shell
puft -h
```

#### Traceback
```
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/puft-test/bin/puft", line 33, in <module>
    sys.exit(load_entry_point('puft==0.4.0a2', 'console_scripts', 'puft')())
  File "/home/alex/.virtualenvs/puft-test/bin/puft", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alex/.virtualenvs/puft-test/lib/python3.10/site-packages/puft-0.4.0a2-py3.10.egg/puft/__init__.py", line 3, in <module>
ModuleNotFoundError: No module named 'puft.errors'
```

**Comment by ryzhovalex** [comment]
#### Temporary fix
You have to export PYTHONPATH to your build folder created at location of setup.py:
```shell
export PYTHONPATH="$HOME/path/to/your/build/lib"
```
